version: '3.8'
services:
  sentinel:
    build: .
    environment:
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - TLS_ENABLED=false
    expose:
      - "8080"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/sentinel.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - sentinel
